---

- name: Upgrade all installed linux packages
  hosts: all
  become: true
  tasks:
  - name: upgrade all package for debian and ubuntu OS
    apt:
      name: "*"
      state: latest
      update_cache: yes
      force_apt_get: yes
    when: ansible_distribution == "Ubuntu" or ansible_distribution == "debian"
    
      
